### PR TITLE
added: privy.io tutorial.

### PR DESCRIPTION
**Pull request by emmaodia**

### CODE REVIEW

**Review by LiorAgnin — COMMENTED** [review]
@emmaodia  IMO, we should also provide an example demonstrating how to create an SCA (Smart Contract Address) using our SDK. What do you think?

**Comment by emmaodia** [comment]
> we should also provide an example demonstrating how to create an SCA (Smart Contract Address) using our SDK

@leonprou Do you mean an example of an SCW using the Flutter SDK? 
We already have one for the Web SDK: https://docs.fuse.io/docs/developers/how-to-guides/how-to-create-an-scw
If yes, for the Flutter SDK, I agree with you. You are right.

**Comment by LiorAgnin** [comment]
> > we should also provide an example demonstrating how to create an SCA (Smart Contract Address) using our SDK
> 
> @leonprou Do you mean an example of an SCW using the Flutter SDK? We already have one for the Web SDK: https://docs.fuse.io/docs/developers/how-to-guides/how-to-create-an-scw If yes, for the Flutter SDK, I agree with you. You are right.

Excellent, I wasn't aware of that. Thank you for the update.

**Review by LiorAgnin — APPROVED** [review]
LGTM!

**Pull request merged**
